# Generated by Django 4.1.3 on 2022-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_newscomment_commented_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnewsarticle',
            name='news_Title',
            field=models.CharField(default='.....', max_length=40),
            preserve_default=False,
        ),
    ]
