# Generated by Django 4.1.3 on 2022-12-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_shortnewsarticle_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='comment_date_and_time',
            new_name='date_and_time',
        ),
        migrations.RenameField(
            model_name='shortnewsarticle',
            old_name='date_and_time_of_article',
            new_name='date_and_time',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='comment_date_and_time',
            new_name='date_and_time',
        ),
    ]
