# Generated by Django 4.1.3 on 2022-12-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_comment_date_and_time_newscomment_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='commented_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.shortnewsarticle'),
        ),
    ]
