# Generated by Django 4.1.3 on 2022-12-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_newscomment_news_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='commented_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shortnewsarticle'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news_comment',
            field=models.CharField(max_length=255),
        ),
    ]
