# Generated by Django 4.1.3 on 2022-11-23 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, 'Name should be min 10 chars')])),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('standard', 'Standard Priority'), ('high', 'High Priority')], max_length=8)),
                ('attached_file_by_author', models.FileField(blank=True, null=True, upload_to='uploads/author_files')),
                ('attached_file_by_executor', models.FileField(blank=True, null=True, upload_to='uploads/executor_files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
