# Generated by Django 4.1.3 on 2022-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file_by_author',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
