# Generated by Django 4.1.3 on 2022-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_attached_file_by_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attached_file_by_executor',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
